name: Compile Arduino Code

on: [push, pull_request]

jobs:
  build-arduino:
    runs-on: ubuntu-latest
    if: contains(github.event.head_commit.message, '[arduino]')
    steps:
      - uses: actions/checkout@v2
      - uses: arduino/compile-sketches@v1
        with:
          libraries: |
            - source-path: ./
  build-esp8266:
      runs-on: ubuntu-latest
      if: contains(github.event.head_commit.message, '[esp8266]')
      steps:
        - name: Checkout code
          uses: actions/checkout@v2
    
        - name: Install Arduino CLI
          uses: arduino/setup-arduino-cli@v1
    
        - name: Install ESP8266 platform
          run: |
            arduino-cli core update-index
            arduino-cli core install esp8266:esp8266
    
        - name: Compile code
          run: |
            arduino-cli compile --fqbn esp8266:esp8266:d1_mini ./examples/Wemos_D1_mini_AM2302_Sensor_Array_Example/Wemos_D1_mini_AM2302_Sensor_Array_Example.ino
