name: Compile Examples

on: [push, pull_request]

jobs:
  build-arduino:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: arduino/compile-sketches@v1
        with:
          libraries: |
            - source-path: ./
          sketch-paths:
            ./examples/AM2302-Sensor_Example/AM2302-Sensor_Example.ino
            ./examples/AM2302_sensor_health_check//AM2302_sensor_health_check.ino
            ./examples/Arduino_Nano_AM2302_Sensor_Array_Example/Arduino_Nano_AM2302_Sensor_Array_Example.ino

  build-esp8266:
    runs-on: ubuntu-latest
    if: contains(github.event.head_commit.message, '[esp8266]')

    strategy:
      fail-fast: false
      
      matrix:
        board:
          - fqbn: esp8266:esp8266:nodemcu
          - fqbn: esp8266:esp8266:d1_mini
        core:
          - version: 3.1.2
          - version: 3.0.2
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Compile ESP8266 examples
        uses: arduino/compile-sketches@v1
        with:
          platforms: |
            - name: esp8266:esp8266
              source-url: https://arduino.esp8266.com/stable/package_esp8266com_index.json
              version: ${{ matrix.core.version }}
          fqbn: ${{ matrix.board.fqbn }}
          libraries: |
            - source-path: ./
          sketch-paths:
            ./examples/Wemos_D1_mini_AM2302_Sensor_Array_Example/Wemos_D1_mini_AM2302_Sensor_Array_Example.ino
            
