name: Generate Doxygen Documentation

on:
  push:
    branches:
      - master  # Passe den Branch an, für den die Dokumentation generiert werden soll

jobs:
  build-docs:
    runs-on: ubuntu-latest

    steps:
      # Checkout des Repositorys
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Installiere Doxygen + graphviz
      - name: Install Doxygen
        run: |
          sudo apt-get update
          sudo apt-get install -y doxygen graphviz

      # Generiere die Dokumentation
      - name: Generate Documentation
        run: doxygen Doxyfile

      # Prüfen, ob der Ordner erstellt wurde
      - name: Verify Documentation and copy pictures to html
        run: |
          ls -la docs
          cp docs/*.jpg docs/html

      # Disable Jekyll
      - name: Disable Jekyll
        run: touch .nojekyll

      # Dokumentation deployen (z.B. in den gh-pages Branch)
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/html

